version: '3'

services:
  web:
    build: .
    environment:
      - DATABASE_URL=postgis://postgres:postgres@db/postgres
    depends_on:
      - db
    volumes:
      - '${DATA_FOLDER}:/usr/src/app/data'

  db:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - web

volumes:
  db-data: {}
