version: '2'

services:
    db:
        image: mdillon/postgis:9.6
        environment:
            - POSTGRES_DB=docker
            - POSTGRES_PASSWORD=postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    web:
        build: .
        image: schools/web:latest
        depends_on:
            - db

    proxy:
        build:
            context: .
            dockerfile: Dockerfile.local
        ports:
            - '80:80'
        depends_on:
            - web

volumes:
    db-data: {}
