version: '2'

services:
  web:
    build: .
    image: schools/web:latest
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - /home/ubuntu/scuole-data:/usr/src/app/data/

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - web
