services:
  web:
    build: .
    image: schools/web:latest
    depends_on:
      - db
    links:
      - db:db

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - web
