services:
  web:
    environment:
      - DATABASE_URL
    build: .
    depends_on:
      - db
    links:
      - db:db

  db:
    image: mdillon/postgis:9.6-alpine
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: {}
